ecodeclub/ekit

- .CHANGELOG.md
- list/linked_list.go
- list/linked_list_test.go
- 实现 Get, 测试, benchmark
- 简化 Add 函数
> LinkedList 实现 Get

- .CHANGELOG.md
- pool/pool_test.go
会有偶发的不通过, 原因应该是, 执行第二次 get 之前, 发生了 gc.
- 加了一个 次数, 记录函数执行了几次
- 根据次数, 来判断应该取到什么值
> 修复 TestPool Test 不稳定的问题

- .CHANGELOG.md
- list/linked_list.go
- list/linked_list_test.go
1. 使用双向循环链表重构linkedlist简化代码逻辑
2. 在测试中使用list接口的AsSlice方法替换linkedListEqual
3. 去掉用if err==nil跳过对零值的比较，有时方法内的零值可能写错
Signed-off-by: longyue0521 <longyueli0521@gmail.com>
> 重构LinkedList

- .CHANGELOG.md
- constrain.go
- slice/aggregate.go
- slice/aggregate_test.go
- 在 Max 和 Min 里面要求提供至少一个元素，是因为如果任何元素都没有的话，我们不知道怎么处理。返回零值并不合适；
另外一个值得讨论的是 types 包。这个我是准备用来放一些公共接口，和泛型约束。目前这里定义了两个泛型约束，
- RealNumber: 实数
- Number：包含了复数的数字
我预计将来在实现树结构的时候，这里会放 Comparable 接口；在实现 HashMap 的时候，会放 Hashable 接口... 这一类的接口，我预期中并不会在专门一个地方使用。例如 Comparable 接口，可以用在树形结构里面，也可以用在 SkipList 里面.
因此需要一个公共的地方来定义类似的接口。
我选择了 types。
> slice: 聚合函数 Max, Min 和 Sum

- .CHANGELOG.md
- .codecov.yml
- slice/contains.go
- slice/diff_test.go
- slice/index.go
- slice/index_test.go
- slice/intersect_test.go
- slice/map.go
- slice/symmetric_diff_test.go
- slice/union_test.go
在 Index 和 Contains 里面的部分方法，我们可以直接调用 xxxFunc 的版本。
唯一的顾虑就是这种重构是否会引入性能的损失。为此我做了一个简单的基准测试来比较：
```go
func BenchmarkIndex(b *testing.B) {
b.Run("loop directly", func(b *testing.B) {
for i := 0; i < b.N; i++ {
IndexByLoop[int]([]int{1, 2, 3, 4, 5, 6}, 5)
}
})
b.Run("delegate to IndexFunc", func(b *testing.B) {
for i := 0; i < b.N; i++ {
Index[int]([]int{1, 2, 3, 4, 5, 6}, 5)
}
})
}
func IndexByLoop[T comparable](src []T, dst T) int {
for i, val := range src {
if val == dst {
return i
}
}
return -1
}
```
这里的 Index 方法已经被我改成了：
```go
func Index[T comparable](src []T, dst T) int {
return IndexFunc[T](src, dst, func(src, dst T) bool {
return src == dst
})
}
```
也就是直接自己循环找，还是调用 IndexFunc 来找，两者进行一个性能比较。
在我的电脑上，运行效果是：
```go
pkg: github.com/gotomicro/ekit/slice
cpu: Intel(R) Core(TM) i7-9750H CPU @ …
```
> slice: 重构 index 和 contains 的方法，直接调用对应Func 版本

- .CHANGELOG.md
- internal/errs/error.go
- internal/slice/delete.go
- internal/slice/delete_test.go
- internal/slice/doc.go
- list/array_list.go
- list/array_list_test.go
- list/concurrent_list_test.go
- list/linked_list.go
- slice/delete.go
- slice/delete_test.go
- slice/map.go
- slice/map_test.go
大多数时候，公共方法我都会设计 error 作为返回值。
Delete 也是如此。
虽然理论上我可以在下标超出范围的时候 panic 或者忽略，但是我认为这种决策应该是由用户来做的，我只需要如实禀告发生了什么。毕竟有些人可能喜欢 panic，有些人喜欢忽略。我不应该越俎代庖做决策。
同时，后续会逐步把公共逻辑迁移进去 internal 里面，包括 error 的创建最好都是通过 errs 包，后期我们引入错误码和错误排查手册的时候会更加方便一点。
我们也应该避免暴露 sentinel error，除非逼不得已
> slice: FilterMap 和 Delete 方法

- .CHANGELOG.md
- pool/task_pool.go
- pool/task_pool_test.go
根据 #80 中讨论尤其是 [讨论1](https://github.com/gotomicro/ekit/pull/80#discussion_r966717803)和[讨论2](https://github.com/gotomicro/ekit/pull/80#discussion_r967837196)
最终我没有采取在[讨论2](https://github.com/gotomicro/ekit/pull/80#discussion_r967837196)提到的**按协程分类创建**策略.原因如下:
1. 代码结构上的重复,只有微小差别,还不好抽出方法来复用.
2. 沿用 #80 中的例子,当协程数达到最大协程数即30时,此时初始协程数的协程们(10个)恰好运行任务结束,它们既没有任务运行也不能退出.当初始数、核心数及最大数的数值很大时更是一个问题.
本次重构采用的是在协程**运行任务结束后**,根据当前协程总数(totalNumOfGo)与初始数(10, initGo),核心数(20, coreGo)的关系来动态随机划分协程.并保证最终稳定在“初始数”即10个. 算法如下:
1. 如果当前协程满足`b.coreGo < b.totalNumOfGo && (len(b.queue) == 0 || int32(len(b.queue)) < b.totalNumOfGo) `则更新协程总数并直接退出
2. 如果当前协程满足`b.initGo < b.totalNumOfGo-b.timeoutGroup.size()`那么当前协程会被设置定时器,在“最大空闲时间”内没接到任务会因为超时而退出.
3. 其他情况要么因为队列中有任务,要么因为当前协程处于“初始数”组中不处理.
timeoutGroup是超时组,有两个作用:
1. …
> 重构TaskPool实现 #80 中讨论的新需求

- .CHANGELOG.md
- queue/delay_queue.go
- queue/delay_queue_test.go
- queue/types.go
新版本：
- 核心是实现了自己定义的  cond，它能够达成 await(time.Duration) 的效果，简化了代码，代价就是会创建额外的 channel
> 延时队列 DelayQueue 实现

- .CHANGELOG.md
- queue/delay_queue.go
- queue/delay_queue_test.go
当前延迟队列有如下问题:
1. 修复CHANGELOG链接(已修复)
2. 添加测试用例修复bug(已修复)
- 当前修复方法,在<-timer.C case 中出队前验证队头元素是否过期.
- 其他方法,去掉<-timer.C case 中的所有代码,让所有人再次去检测一次队头,可能造成不公平,恰巧有新协程调用dequeue直接将队头出队了,其他人白白等待.
3. 可读性问题
- 在broadcast和SignalCh可见性不一致(已修复)
- 在broadcast和SignalCh中暗中解锁,极大影响Dequeue和Enqueue的可读性.推荐标准库sync.Cond中的做法,解锁后再加锁,这样调用的地方也会有解锁步骤,可读性更好.
Signed-off-by: longyue0521 <longyueli0521@gmail.com>
> 延迟队列: 修改已知问题

- .CHANGELOG.md
- go.mod
- go.sum
- queue/concurrent_array_blocking_queue.go
-主要改造了concurrent_array_blocking_queue的实现，将原来基于cond的实现改造成基于semaphore的实现
> queue: 基于semaphore的并发阻塞队列实现

- .CHANGELOG.md
- pool/task_pool_test.go
1. 重构TestOnDemandBlockTaskPool_States,只关注是否能读取数据,读取的数据是否为零值,返回的chan是否被关闭等不再校验数据内容.
2. 完善Taskpool有限状态机
3. 添加t.Parallel() 尽可能利用Go测试框架的并发特性加速测试用例运行
4. TestOnDemandBlockTaskPool_In_Closing_State/Shutdown
> 重构task pool相关测试用例

- .CHANGELOG.md
- sqlx/scan.go
- sqlx/scan_test.go
> 添加ScanRows 和 ScanAll方法

- .CHANGELOG.md
- internal/tree/red_black_tree.go
- mapx/hashmap.go
- mapx/treemap.go
- mapx/treemap_test.go
- mapx/types.go
- set/set_test.go
- set/treeset.go
将原本 Remove 方法改成了 Delete 方法，这算是一个不兼容的修改。不过之前 review 代码的时候没有注意，也没得办法
> mapx: TreeMap 添加 Keys 和 Values 方法

- .CHANGELOG.md
- pool/task_pool.go
> refacor/Taskpool: 统一内外中断信号+修复bug

- .CHANGELOG.md
- bean/copier/copy.go
- bean/copier/reflect_copier.go
- bean/copier/reflect_copier_test.go
我直接采用了可行方案，引入 options 结构体。
需要忽略的字段需要有个地方存储，我想过直接把需要忽略的字段加在方法后面，但这显然不是个好主意。如果后续又有其他的附加功能，那这种设计就要继续在方法后面加参数。
引入 options 结构体后，在调用方法的时候，可以使用 option 设计模式，自主决定需要怎么修改 options 结构体的参数（触发哪些附加功能）。
忽略字段的逻辑，安排在了拷贝结点的过程中，如果发现结构体的属性名在需要忽略的字段里，就跳过这个属性的拷贝。
我把之前的差不多每个有效情况的测试用例都复制了一份，添加了一些忽略字段的场景。
> copier: ReflectCopier 支持忽略字段

- .CHANGELOG.md
- syncx/map.go
- syncx/map_test.go
> 重构: syncx: map

- .CHANGELOG.md
- mapx/builtin_map.go
- mapx/builtin_map_test.go
- mapx/multi_map.go
- mapx/multi_map_test.go
- set/set.go
我们会在 mapx 里面提供陆续多个 map 的装饰器，比如说 MultiMap 就是典型的一个实现。因此将 map 转化为一个 builtmap 之后，就可以使用这些实现。
> mapx: 支持 builtinMap，用于接入其它装饰器实现

- .CHANGELOG.md
- slice/contains.go
- slice/contains_test.go
- slice/diff.go
- slice/find.go
- slice/find_test.go
- slice/index.go
- slice/index_test.go
- slice/map.go
- slice/symmetric_diff.go
- slice/types.go
1. 引入 matchFunc
2. 简化 slice 中查找类型的 API
3. 引入 Find 和 FindAll 方法
> slice: 重构 slice 中使用 equalFunc 的方法

- .CHANGELOG.md
- stringx/string.go
- stringx/string_test.go
Closes #214 
注意使用非安全的方式转换时一定要注意以下三点
- 确保传入的字符串和字节切片的生命周期足够长，不会在转换后被释放或修改。
- 确保传入的字符串和字节切片的长度和容量是一致的，否则可能导致访问越界。
- 不要对转换后的字节切片或字符串进行修改，因为它们可能与原始的字符串或字节切片共享底层的内存。
> [feat](stringx) 新增unsafe 转换 string 和 []byte

- queue/errs.go
当我需要一个固定容量的队列，并且希望在队列满了之后淘汰掉优先级最低的元素的时候，我就需要知道这个错误。
> queue: 暴露超出容量错误

- .CHANGELOG.md
- syncx/limit_pool.go
- syncx/limit_pool_test.go
通过控制一段时间内Pool的最大申请次数(可串行、可并行)来间接控制住Pool的最大使用量
> syncx(feat): 添加具有最大申请次数限制的Pool

- iox/json_reader.go
- iox/json_reader_test.go
在很多时候，我们需要将一个结构体在经过序列化之后，作为一个 reader 传入到别的方法里面。
为了避免写重复代码，我提供了一个封装。
毕竟在没有这个封装的情况下，还是过于垃圾了。
> iox: 添加 iox.JSONReader

- net/httpx/log_round_trip.go
- net/httpx/log_round_trip_test.go
- net/httpx/request.go
- net/httpx/request_test.go
- net/httpx/response.go
- net/httpx/response_test.go
在使用原生的 http 包的时候，充斥着大量的错误处理。这里我将整个过程简化了，只有在发起最终调用的时候，才会返回 error。
所谓的最终调用，就是指真正尝试解析 response 的时候，才会返回 error。在这之前，可以保持丝滑的链式调用。
> httpx: Request 和 Response 初步设计

- mapx/builtin_map.go
- mapx/builtin_map_test.go
- mapx/hashmap.go
- mapx/hashmap_test.go
- mapx/linkedmap.go
- mapx/linkedmap_test.go
- mapx/multi_map.go
- mapx/multi_map_test.go
- mapx/treemap.go
- mapx/treemap_test.go
- mapx/types.go
> 新增mapi.Len()方法

- .CHANGELOG.md
- randx/rand_code.go
- randx/rand_code_test.go
1. 支持字符类型自由组合
2. 增加对特殊字符的支持
3. 增加函数RandStrByCharset，可以自定义字符集
4. 增加对length小于0的异常处理
5. 增加benchmark
> 重构: randx.RandCode 代码

- list/copy_on_write_array_list.go
- list/copy_on_write_array_list_test.go
> feat: 添加copy on write list实现

- condition.go
- condition_test.go
此 PR 添加了一个 `IfThenElse` 函数，它根据条件返回对应的泛型结果。该函数允许在单行代码中实现类似三元运算符的功能。
- `IfThenElse[T any](condition bool, trueValue, falseValue T) T` 根据布尔条件返回 `trueValue` 或 `falseValue`。
- 支持泛型，能够处理任意类型的输入。
- 请注意，`trueValue` 和 `falseValue` 在传入时即会访问，因此调用方需确保它们的合法性。
```go
result := IfThenElse(true, "Success", "Failure")
fmt.Println(result) // 输出: Success
> 添加 `IfThenElse` 函数返回泛型结果

- go.sum
- net/httpx/request.go
- net/httpx/request_test.go
修改一个bug: http.NewRequestWithContext()返回error时，req为nil，后面调用JSONBody()等方法会发送panic
> httpx:增加error判断

- .devcontainer/devcontainer.json
- .github/workflows/go.yml
- Makefile
- spi/testdata/user_service/a.go
- spi/testdata/user_service2/a/a.go
- spi/testdata/user_service2/b/b.go
- spi/testdata/user_service3/a.go
1. 增加devcontainer, 方便windows用户开发并且可以统一开发环境的golang version
2. 修复编译参数不统一导致的spi test在make ut中无法通过的问题
> 为ekit增加 devcontainer，修复spi test在make ut中无法通过的问题

- mapx/map.go
- mapx/map_example_test.go
- mapx/map_test.go
#275 mapx: 支持 Merge 方法
增加两个函数：
1. Merge 直接合并，存在冲突的键值对则直接覆盖
2. MergeFunc 合并，存在冲突的键值对需要指定合并方式
> mapx 增加 merge 方法
